#!/bin/bash

# This script will auto-install Arch Linux the way I like

read -p " Enter a name for the computer " comp 
tzselect > tz.tmp
echo 
read -p "Enter partionsize in gb, separated by space (swap & root)" -a SIZE

re='^[0-9]+$'
if ! [ ${#SIZE[@]} -eq 2 ] || ! [[ ${SIZE[0]} =~ $re ]] || ! [[ ${SIZE[1]} =~ $re ]] ; then
    SIZE=(12 25);
fi

timedatectl set-ntp true

dd if=/dev/urandom of=/dev/sda
cat <<EOF | fdisk /dev/sda
o
n
p


+200M
n
p


+${SIZE[0]}G
n
p


+${SIZE[1]}G
n
p


w
EOF
partprobe
lsblk

mkfs.ext4 /dev/sda4
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mount /dev/sda3 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mkdir /mnt/home
mount /dev/sda4 /mnt/home


pacstrap /mnt base base-devel

genfstab -U /mnt >> /mnt/etc/fstab
cat tz.tmp > /mnt/tzfinal.tmp
rm tz.tmp
curl https://raw.githubusercontent.com/Rhylx/RBS/master/chroot_rbs > /mnt/chroot.sh && arch-chroot /mnt bash chroot.sh && rm /mnt/chroot.sh

echo $comp > /mnt/etc/hostname && rm comp

echo  "Reboot computer?"
select yn in "Yes" "No"; do
  case $yn in
	Yes ) reboot;;
	No  ) exit ;;
  esac
done 
clear
