#!/bin/bash

# This is the main script of RBS : it will auto-install and configure all programs that I dayli use

read -p "Enter the username of your account: " name
read -sp "Enter a password for your account: " pass1
printf '\n'
read -sp "Retype your password: " pass2
printf '\n'

while [ $pass1 != $pass2 ]
do
	read -sp "Passwords do not match. Enter your password again: " pass1
	printf '\n'
	read -sp "Retype your password: " pass2
	printf '\n'
done

echo -e "Adding user "$name""
useradd -m -g wheel -s /bin/bash $name >/dev/tty6
echo "$name:$pass1" | chpasswd >/dev/tty6

echo "Refreshing Arch Keyring..."
pacman --noconfirm -Sy archlinux-keyring >/dev/tty6

echo "Getting program list..."
curl https://raw.githubusercontent.com/Rhylx/RBS/master/progs.csv > /tmp/progs.csv
rm /tmp/aur_queue &>/dev/tty6
count=$(cat /tmp/progs.csv | wc -l)
n=0
installProgram() { ( (pacman --noconfirm --needed -S $1 &>/dev/tty6 && echo $1 installed.) || echo $1 >> /tmp/aur_queue) || echo $1 >> /tmp/larbs_failed ;}

for x in $(cat /tmp/progs.csv | awk -F, {'print $1'})
do
	n=$((n+1))
	echo "Downloading and installing program $n out of $count: $x..."
	echo "The first programs will take more time due to dependencies. You can watch the output on tty6."
	printf '\n'
	printf '\n'
	installProgram $x >/dev/tty6
done

echo "Preparing the user script (sudoers)..."
curl https://raw.githubusercontent.com/Rhylx/RBS/master/sudoers_installation > /etc/sudoers
cd /tmp
curl https://raw.githubusercontent.com/Rhylx/RBS/master/rbs_user > /tmp/rbs_user
sudo -u $name bash /tmp/rbs_user
rm -f /tmp/rbs_user

echo "Initialising git "
git config --global user.email "redbull11570@gmail.com"
git config --global user.name "Rhylx"

echo "Installing st from source..."
cd /tmp
rm -rf st
git clone --depth 1 https://github.com/Rhylx/st.git
cd st
make
make install
cd /tmp

echo "Initialising shortcut-sync"
shortcuts.sh

echo "Enabling Network Manager..."
systemctl enable NetworkManager
systemctl start NetworkManager

echo "Enabling i8kutils for fan..."
echo "set config(auto)	1" >> /etc/i8kutils/i8kmon.conf
systemctl enable i8kutils.service
systemctl start i8kutils.service

echo "Getting rid of that retarded error beep sound..."
rmmod pcspkr
echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
echo " Updating sudoers ( end of installation ): "
curl https://raw.githubusercontent.com/Rhylx/RBS/master/sudoers > /etc/sudoers

echo "Installation finished. To start i3, run command : startx"
