#!/bin/sh

# This is the main script of RBS : it will auto-install and configure all programs that I daily use

# Is first meant for arch, but will then be extended to void and debian
# Goal of this script :
#
# -> Install all programs from prog.csv:
#       graphically try to do something like \green{INSTALLATION CONFIRMED}/\red{ERROR} for each soft
# -> Install keyboard layout
# -> Installing dotfiles (which of course need to be reviewed and updated...)
# -> Setup doas (instead of sudo)
# Try to do these steps manually and write it all again...


mkdir /tmp/tmprbs
read -p "Which aurhelper would you like to install (default is yay): " aurhelper


[ -z "$aurhelper" ] && aurhelper="yay"

internet()
{
	echo "Testing internet connection..."
	ping -c 2 www.example.com 2>&- >/dev/null || (echo "You're not connected to the internet. Check out that NetworkManager is started" && false)
}

pimp_pacman(){
	grep "^Color" /etc/pacman.conf >/dev/null || sed -i "s/^#Color$/Color/" /etc/pacman.conf
}

refresh_keyrings(){
	sudo pacman --noconfirm --needed -Sy archlinux-keyring >/dev/null 2>&1
}

install_yay(){
	[ -f "/usr/bin/$aurhelper" ] || (
	cd /tmp/tmprbs
	rm -rf /tmp/tmprbs/"$aurhelper"*
	curl -sO https://aur.archlinux.org/cgit/aur.git/snapshot/"$aurhelper".tar.gz &&
	tar -xvf "$aurhelper".tar.gz >/dev/null 2>&1 &&
	cd "$aurhelper" &&
	makepkg --noconfirm -si >/dev/null 2>&1
	cd /tmp/tmprbs)
}

writing_bold_green(){
	tput bold ; tput setaf 2
	echo $1
	tput sgr0
}

writing_bold_red(){
	tput bold ; tput setaf 1
	echo $1
	tput sgr0
}

installer(){
	echo -n "Installing $1$ ...    "
	sudo pacman --noconfirm --needed -S "$1" >/dev/null 2>&1 && writing_bold_green "[DONE]" || writing_bold_red "[ERROR]"
}


aur_installer(){
	echo -n "Installing $1$ ...    "
	$aurhelper --noconfirm -S "$1" >/dev/null 2>&1 && writing_bold_green "[DONE]" || writing_bold_red "[ERROR]"
}

install_progs(){
	while IFS=, read -r tag prog comment; do
		case "$tag" in
			"A") aur_installer $prog ;;
			*) installer $prog ;;
		esac
	done < progs.csv
}












clear_tmprbs(){
	sudo rm -rf /tmp/tmprbs >/dev/null 2>&1
}


remove_all(){
	echo "An error occured"
	clear_tmprbs
}



internet && pimp_pacman && refresh_keyrings && install_yay && install_progs && clear_tmprbs || remove_all


