#!/bin/sh

# This script will auto-install Arch Linux the way I like


#I/O part :


echo -e "Here is the output of lsblk : \n"
lsblk
echo
read -p "Enter drive you want it to install on (only a if on /dev/sda): " -a X
echo "Assuming that there will be 4 partitions: boot, swap, / and /home"
read -p "Enter partionsize in gb , separated by a space (swap & /): " -a SIZE

#Functionnal part :

export DIST=$(./detect_distrib) #once installation done write this to /etc/environment

internet()
{
	ping -c 2 www.example.com 2>&- >/dev/null || (echo "You're not connected to the internet. Check out your connection" && false)
}

partition(){
cat <<EOF | 2>&- >/dev/null fdisk -W always /dev/sd$X || (echo "Either does the drive not exist or the partition sizes are too big" && false)


o
n
p


+200M
n
p


+${SIZE[0]}G
n
p


+${SIZE[1]}G
n
p


a
1
w
EOF
}


format_part(){
	mkfs.ext4 -qF /dev/sd${X}4 >/dev/null 2>&1
	mkfs.ext4 -qF /dev/sd${X}3 >/dev/null 2>&1
	mkfs.ext4 -qF /dev/sd${X}1 >/dev/null 2>&1
	mkswap /dev/sd${X}2 >/dev/null 2>&1
	swapon /dev/sd${X}2 >/dev/null 2>&1
}


mount_part(){
	mount /dev/sd${X}3 /mnt
	mkdir /mnt/boot
	mount /dev/sd${X}1 /mnt/boot
	mkdir /mnt/home
	mount /dev/sd${X}4 /mnt/home
}


install_dist(){
echo "hi"
}

gen_fstab(){


}

chrootin(){

}


root_passwd(){

}

create_user(){


}

grub_install(){


}

remove_all(){
	umount /mnt/home >/dev/null 2>&1
	umount /mnt/boot >/dev/null 2>&1
	umount /mnt >/dev/null 2>&1
	swapoff /dev/sd${X}2 >/dev/null 2>&1
	cat << EOF | 2>&- >/dev/null fdisk -W always /dev/sd$X


o
n
p



w
EOF
	echo "An error has occured. Fix the issue and rerun this script."
}



internet && partition && format_part && mount_part && install_dist || remove_all



read -p " Enter a name for the computer: " comp
tzselect > tz.tmp

timedatectl set-ntp true

partprobe
lsblk

lsblk

pacstrap /mnt base base-devel

genfstab -U /mnt > /mnt/etc/fstab
cat tz.tmp > /mnt/tzfinal.tmp
rm tz.tmp
curl https://raw.githubusercontent.com/Rhylx/RBS/master/chroot_rbs > /mnt/chroot.sh && arch-chroot /mnt bash chroot.sh && rm /mnt/chroot.sh

echo "$comp" > /mnt/etc/hostname


echo  "Reboot computer?"
select yn in "Yes" "No"; do
	case $yn in
	Yes ) reboot;;
	No  ) exit ;;
  	esac
done
