#!/bin/sh

echo -e "Here is the output of lsblk : \n"
lsblk
echo
read -p "Enter drive you want it to install on (only a if on /dev/sda): " -a X
read -p "Enter partionsize in gb, separated by a space (swap & /): " -a SIZE

#Functionnal part :



export "DIST=$(./detect_distrib)$" #once installation done write this to /etc/environment


internet()
{
	ping -c 2 www.example.com 2>&- 1>/dev/null || (echo "You're not connected to the internet. Check out your connection" && false)
}

partition(){
cat <<EOF | 2>&- 1>/dev/null fdisk /dev/sd$X || (echo "Either does the drive not exist or the partitions sizes are too big" && false)


o
n
p


+200M
n
p


+${SIZE[0]}G
n
p


+${SIZE[1]}G
n
p


a
1
w
EOF
}


format(){
echo "hi"
}


mount(){


}


install(){


}

gen_fstab(){


}

chrootin(){

}


root_passwd(){

}

create_user(){


}

grub_install(){


}

remove_all(){
echo "An error has occured. Fix the issue and rerun this script."
}



internet && partition && format || remove_all


