#!/bin/sh


echo -e "Here is the output of lsblk : \n"
lsblk
echo
#read -p "Enter drive you want it to install on (only a if on /dev/sda): " -a X
echo "Assuming that there will be 4 partitions: boot, swap, / and /home"
#read -p "Enter partionsize in gb , separated by a space (swap & /): " -a SIZE
X=a
SIZE=2 10
#Functionnal part :



export "DIST=$(./detect_distrib)$" #once installation done write this to /etc/environment


internet()
{
	ping -c 2 www.example.com >/dev/null 2>&1 || (echo "You're not connected to the internet. Check out your connection" && false)
}

partition(){
cat <<EOF | >/dev/null 2>&1 fdisk /dev/sd$X || (echo "Either does the drive not exist or the partition sizes are too big" && false)


o
n
p


+200M
n
p


+${SIZE[0]}G
n
p


+${SIZE[1]}G
n
p


a
1
w
EOF
}


format(){
	mkfs.ext4 -qF /dev/sd$X4	>/dev/null 2>&1
	mkfs.ext4 -qF /dev/sd$X3 >/dev/null 2>&1
	mkfs.ext4 -qF /dev/sd$X1 >/dev/null 2>&1
	mkswap /dev/sd$X2 >/dev/null 2>&1
	swapon /dev/s$X2 >/dev/null 2>&1
}


mount(){
echo "hi"
	mount /dev/sd$X3 /mnt
	mkdir /mnt/boot
	mount /dev/sd$X1 /mnt/boot
	mkdir /mnt/home
	mount /dev/sd$X4 /mnt/home
}

remove_all(){
swapoff /dev/sd$X2 >/dev/null 2>&1
>/dev/null 2>&1 fdisk /dev/sd$X <<EOF


o
n
p



w
EOF
echo "An error has occured. Fix the issue and rerun this script."
}


#remove_all

internet && partition && format && mount || remove_all
