#!/bin/sh
# This script is meant to easily deploy searx on a openbsd system

# First we install all we'll need :

pkg_add python3 py3-virtualenv py3-lxml py3-pip py3-babel py3-gunicorn libxml nginx 
ln -s /usr/local/bin/pip* /usr/local/bin/pip

# Then let's create a searx user :

useradd -md /usr/local/searx -s /bin/sh searx
chown -R searx:searx /usr/local/searx

# Now we want to install searx :

su -l -s /bin/sh searx -c "git clone https://github.com/searx/searx.git /usr/local/searx/searx-src"
su -l -s /bin/sh searx -c "python3 -m venv /usr/local/searx/searx-pyenv"
su -l -s /bin/sh searx -c "echo '. /usr/local/searx/searx-pyenv/bin/activate' >>  /usr/local/searx/.profile"
cat /usr/local/searx/.profile | awk '/^PATH/{sub(/$/,":\/usr\/local\/searx\/.local\/bin")};{print}' > /usr/local/searx/temp 
chown searx:searx /usr/local/searx/temp
su -l -s /bin/sh searx -c "mv /usr/local/searx/temp /usr/local/searx/.profile"
su -l -s /bin/sh searx -c "pip3 install -U pip setuptools wheel"
su -l -s /bin/sh searx -c "cd /usr/local/searx/searx-src && pip install -e ." 

# Configuring searx :
# Here should be directly cp the config files...
mkdir /etc/searx
cp /usr/local/searx/searx-src/searx/settings.yml /etc/searx/settings.yml
sed -i -e "s/ultrasecretkey/$(openssl rand -hex 16)/g" "/etc/searx/settings.yml"


