#!/bin/ksh
#
# $OpenBSD: gitea.rc,v 1.5 2019/02/14 10:08:53 pvk Exp $

daemon="/usr/local/searx/searx-pyenv/bin/gunicorn"
daemon_user="searx"
daemon_flags=" -b 127.0.0.1:8888 -w 3 searx.webapp:app"

. /etc/rc.d/rc.subr

rc_bg=YES
pexp="/usr/local/searx/searx-pyenv/bin/python3 /usr/local/searx/searx-pyenv/bin/gunicorn -b 127.0.0.1:8888 -w 3 searx.webapp:app"
rcexec="su -l -s /bin/sh ${daemon_user} -c"
rc_cmd $1
