#!/bin/ksh
#
# $OpenBSD: gitea.rc,v 1.5 2019/02/14 10:08:53 pvk Exp $

ncpu=$(sysctl hw.ncpu | cut -d '=' -f2)
daemon="/usr/local/bin/gunicorn"
daemon_user="searx"
daemon_flags=" -b 127.0.0.1:8888 -w ${ncpu} searx.webapp:app"

. /etc/rc.d/rc.subr

rc_bg=YES
pexp="/usr/local/searx/searx-pyenv/bin/python3 ${daemon} -b 127.0.0.1:8888 -w ${ncpu} searx.webapp:app"
rcexec="su -l -s /bin/sh ${daemon_user} -c"
rc_cmd $1
